# Generated by Django 5.1.7 on 2025-10-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("renter", "0012_alter_bike_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="bike",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bike",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
